### ISSUE TITLE
receive these messages

### ISSUE THREAD

**Issue by victorfhrc** [Kizuno18/emesson-bot#1]
"[188787680] [21:53:32] Thread #1 : Waiting for element >CSS> #root > div > div > div > div.Layout-sc-nxg1ff-0.video-player > div > div > div > div > div.Layout-sc-nxg1ff-0.dKPQbY > div.Layout-sc-nxg1ff-0.efbVt > span"

**Comment by Kizuno18** [comment]
neet to be updated, if you have the knowledge, just edit project.xml
